### PR TITLE
Separate simulator from main.cpp

### PR DESCRIPTION
**Pull request by cbachhuber**
Start of cleaning up demo/main.cpp

### CODE REVIEW

**Comment by TheCodez** [comment]
I think this is change is adding more complexety than needed. Given the simplicity of the simulator class I think it's better to just have a simulator.h file besides main.cpp instead of making the simulator its own library. (The image creation function would be in another header)
What do you think?

**Comment by cbachhuber** [comment]
You're right, I went too far here, thinking about future extensions. Let's not do that now. Fixed according to your suggestion.

**Comment by cbachhuber** [comment]
I would directly create an `image_creation.h` in this PR as well, ok?

**Comment by TheCodez** [comment]
Sure go ahead :)

**Comment by cbachhuber** [comment]
:+1: 

I moved macro `#define _USE_MATH_DEFINES` to image_creation.h. I guess it should be there because of M_PI. Does that still work on windows?

**Comment by TheCodez** [comment]
Yes that still works. You should add `simulator.h` and `image_creation.h` to add_executable, otherwise they don't show up inside Visual Studio.

**Comment by cbachhuber** [comment]
Good point. I think in modern Cmake, header files should [not directly be referenced in `add_executable`](https://stackoverflow.com/a/13703725/7260972).

As suggested in the stackoverflow answer above, we could move them to a separate include directory and make that available through `target_include_directories`. Does that work for you?

**Comment by TheCodez** [comment]
Yeah sure.

**Comment by cbachhuber** [comment]
Cool, implemented :+1:

**Comment by TheCodez** [comment]
Could you include the headers directly in add_executable and move them to main.cpp. They still don't show up in Visual Studio :/

**Comment by cbachhuber** [comment]
Done, is it now ok?

**Comment by TheCodez** [comment]
Yes, thank you!

**Pull request merged**
