### PR TITLE
Suppress warnings in dependencies

### PR DESCRIPTION
**Pull request by cbachhuber**
My build output is cluttered by messages such as 

```
/usr/include/glm/ext/vec1.hpp(141): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
```

Since these warnings do not stem from our code, I suggest that we treat them as system libraries (cmake's way of suppressing such warnings).

### CODE REVIEW

**Comment by TheCodez** [comment]
This has no effect on windows. Could you try the settings in 
https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/CMakeLists.txt#L90-L92
and see if that works on linux? This way those warnings are removed.

**Comment by cbachhuber** [comment]
Your suggestion also works on Linux, thanks for the hint. However, I think it's not a clean solution, because it will also suppress warnings within our code. That's probably the reason why you have commented that out on master.

Cmake's 'system' flag not having an effect in visual studio seems to be a [ known issue](https://developercommunity.visualstudio.com/content/problem/12991/cmakeopen-folder-include-directoriessystem-still-h.html). As this PR has no negative effect on Windows and correctly resolves the issue on Linux, I see no reason not to merge it. What do you think?

**Comment by TheCodez** [comment]
Sure I see no reason not to merge it if it helps on linux. One question, why is SYSTEM flag added to cuda toolkit not glm where the error comes from?

**Comment by cbachhuber** [comment]
This flag affects all libraries in the `include_directories` statement, see [cmake documentation](https://cmake.org/cmake/help/v3.0/command/include_directories.html). It should be positioned before the include folders. And actually, now I see the issue that in this statement we also have the `include` folder of our library. Didn't notice this before.

Let me try to resolve this.

**Comment by cbachhuber** [comment]
I separated the local include from the system includes. Imho, that's also giving  a better separation. What do you think of that?

**Comment by TheCodez** [comment]
Definitely the right thing to do, thank you!

**Pull request merged**
