### PR TITLE
Evaluate accuracy

### PR DESCRIPTION
**Pull request by cbachhuber**
Addressing #23: First version of accuracy evaluation. The evaluator assigns clusters to the closest ground truth vehicles. For the overall summary, it does not yet distinguish vehicles. For simplicity, it lumps the errors from all vehicles into shared cumulative variables.

### CODE REVIEW

**Comment by TheCodez** [comment]
Awesome work as always 👍 
A few changes and this is ready to go.

**Comment by cbachhuber** [comment]
Good points, thanks for those improvements! Merged.

**Comment by TheCodez** [comment]
You can add the std::optional changes to this pr as well if you want.

**Comment by cbachhuber** [comment]
Thanks, done :)

**Comment by TheCodez** [comment]
I checked this out and sadly Visual Studio has no `<experimental/optional>` for C++ 14.

**Comment by cbachhuber** [comment]
... and I expected that for once, we would not have issues with MSVC :sweat_smile:

Which version of Visual studio are you using? Could it be an older one that does not yet support std::experimental?

If we cannot solve this through Visual studio, I see a couple of options here:
- Use [boost's optional](https://www.boost.org/doc/libs/1_61_0/libs/optional/doc/html/index.html). This would introduce an additional dependency, however
- Implement our own optional (it's a really simple class)/copypaste from e.g. [here](https://github.com/akrzemi1/Optional)
- Import the above repo as git submodule
- Do not use optional (least favorable for imho)

**Comment by TheCodez** [comment]
I would remove optional from this pr.
Given there’s need to use optional every in the codebase and the small use case here, I see no reason to add another dependency.

**Comment by TheCodez** [comment]
I tested with Visual Studio 2019 and the error persists. If there are more cases where optional could be used I would go with option 2 or 3.

**Comment by cbachhuber** [comment]
Thanks for checking. I removed optional, should be ready to merge now.

If I find time, I'll introduce optional to this repo. But first, I think I want to tidy up in folder dogm/demo ;)

**Pull request merged**
