### PR TITLE
Separate precision evaluator

### PR DESCRIPTION
**Pull request by cbachhuber**
- Split precision evaluator into header and source file
- Move to folder utils
- Minor refactoring inside precision evaluator
- Create separate cmake target for demo utils. 
  - Plan is to add other utilities such as image_creator and simulator to target `utils` in follow-up PRs
  - Additional motivation for the separate target is that I would like to introduce unit tests for the utilities, which is best done with a separate target for the utilities.
  - With the above two reasons, I think we have enough justification to add this cmake overhead. Do you agree?

With the current CMake setup, you should be able to see the new header in visual studio. Is that correct?

### CODE REVIEW

**Comment by TheCodez** [comment]
Yes they are visible. We have now have one problem with M_PI missing again.
We should add `add_definitions(-D_USE_MATH_DEFINES)` to CMake to get around order related problems.

**Comment by cbachhuber** [comment]
Ah, right! Thanks for the suggestion, I put it to the CMakeLists.txt in the demo folder. This way, it will affect everything inside demo. Or do you prefer putting it to the toplevel CmakeLists?

**Comment by TheCodez** [comment]
This is fine. I think it's better to only use it where needed.

**Comment by TheCodez** [comment]
Thanks a lot!

**Pull request merged**
